/**
 * Build and source provenance identity for Alpha Coach API
 * Automatically generated by scripts/build-api-bundle.js
 */
export interface BuildInfo {
  version: string;
  gitCommit: string;
  buildTimestamp: string;
  environment: string;
  sourceOrigin: string;
}

export const BUILD_INFO: BuildInfo = {
  version: "1.0.5",
  gitCommit: "ac5eca9caad30491100d96123413334f597d5bdc",
  buildTimestamp: "2026-09-27T01:40:38.518Z",
  environment: process.env.NODE_ENV || 'production',
  sourceOrigin: 'backend/src'
};
