/**
 * Build and source provenance identity for Alpha Coach API
 * Automatically generated by scripts/build-api-bundle.js
 */
export interface BuildInfo {
  version: string;
  gitCommit: string;
  buildTimestamp: string;
  environment: string;
  sourceOrigin: string;
}

export const BUILD_INFO: BuildInfo = {
  version: "1.0.5",
  gitCommit: "beb5d1405b9d70d6d71d571d3d991f8d4ca28c21",
  buildTimestamp: "2026-09-27T03:02:24.269Z",
  environment: process.env.NODE_ENV || 'production',
  sourceOrigin: 'backend/src'
};
