/**
 * Build and source provenance identity for Alpha Coach API
 * Automatically generated by scripts/build-api-bundle.js
 */
export interface BuildInfo {
  version: string;
  gitCommit: string;
  buildTimestamp: string;
  environment: string;
  sourceOrigin: string;
}

export const BUILD_INFO: BuildInfo = {
  version: "1.0.5",
  gitCommit: "abf6c7c5dde35cd1deba0abaee4efee38fde7cdd",
  buildTimestamp: "2026-09-27T17:50:35.198Z",
  environment: process.env.NODE_ENV || 'production',
  sourceOrigin: 'backend/src'
};
